### ISSUE TITLE
Add Bolt tasks

### ISSUE THREAD

**Issue by treydock** [sensu/sensu-puppet#1147]
There are several bolt tasks that would be useful:

- [x] Manage events (resolve, delete) #1153 
- [x] Manage silencing #1153 
- [x] Execute checks #1153
- [x] Agent events #1153
- [x] List outdated assets #1162 
- [x]  Deploy agent defining backend, namespace and subscription #1153 
- [x] Inventory from sensu #1164

**Comment by calebhailey** [comment]
And above all - use Bolt to deploy the agent, minimally configuring the backend(s) the agent should connect to, the namespace it should join, and the subscriptions it should subscribe to. 👍

**Comment by treydock** [comment]
Looks like might be possible to define bolt inventory using external sources so in theory could set bolt inventory to be pulled from sensuctl: https://groups.google.com/forum/#!topic/puppet-users/cDYbir1JlgQ
