### ISSUE TITLE
v3 - Support sensu-go

### ISSUE THREAD

**Issue by ghoneycutt** [sensu/sensu-puppet#901]
What's needed to support sensu-go

- [x] document development procedures for maintaining support for sensu-go and sensu v1.
- [x] document config approach - backend vs local config
- [x] base module to manage files, packages, services, etc.
- [x] documentation with puppet-strings
- [x] README
- [x] extension provider code is cleaned up after https://github.com/sensu/sensu-go/issues/1767 is fixed
- [x] support resource purging - https://github.com/sensu/sensu-puppet/pull/954
- [ ] types and providers
  - [x] asset
    - [ ] `ensure => absent` works - https://github.com/sensu/sensu-go/issues/988
  - [x] check
  - [x] cluster
  - [x] config
  - [x] entity
  - [x] environment
  - [x] event
  - [x] extension
  - [x] filter
  - [x] handler
  - [x] hook
  - [x] mutator
  - [x] organization
  - [x] role
  - [x] silenced
  - [ ] user
    - [ ] password support works - https://github.com/sensu/sensu-go/issues/1437
  - [x] api_validator
- [x] major platforms
  - [x] EL7
  - [x] Debian 9
  - [x] Ubuntu 16.04
- [ ] minor platforms
  - [x] EL 6
  - [x] Debian 7 is removed - https://github.com/sensu/sensu-puppet/issues/904
  - [x] Debian 8
  - [x] Debian 9
  - [x] Ubuntu 16.04
  - [x] Ubuntu 18.04
  - [x] Amazon 2017.3
  - [x] Amazon 2018.3 (travis only not vagrant)
  - [x] Amazon 2

For an item to be checked, it needs the following if applicable.
* spec tests
* acceptance tests (beaker/serverspec)
* Vagrant instance for each platform

**Comment by treydock** [comment]
@ghoneycutt Where is environment documented?  Also may not need to do anything for `event`, looks like entirely informational and nothing that can be changed with `sensuctl`.

**Comment by treydock** [comment]
@ghoneycutt Nevermind about environment, found under RBAC section.

**Comment by treydock** [comment]
@ghoneycutt Any references for `extension`?  Also do we want to add a type for `event`?  `event` seems like something sent by checks or on a more ad-hoc basis.

**Comment by ghoneycutt** [comment]
I think extension is just for v1 of sensu as it is not listed in the v2 docs

**Comment by ghoneycutt** [comment]
@treydock Event's can be deleted and resolved, so we should have a type/provider for them.

**Comment by treydock** [comment]
@ghoneycutt Can check off EL6 and Ubuntu 14.04.  The tests for Ubuntu 18.04 work in Docker and Vagrant is fixed with #915.

**Comment by treydock** [comment]
@ghoneycutt For the `config` type, the only things it can change in `sensuctl` is default organization, environment and output format.  AFAICT our use of `sensuctl create -f` bypasses default organization and environment so those are defaulted in the individual types.

I do notice that right now if a system in provisioned and the password changed later, `sensuctl configure` won't get re-run.

**Comment by ghoneycutt** [comment]
@treydock Added documentation with puppet-strings to the list.

https://puppet.com/docs/puppet/5.5/puppet_strings_style.html#resource-types

**Comment by treydock** [comment]
May need to add extension back, it appears to be something that can be managed with sensuctl.

**Comment by ghoneycutt** [comment]
Put it back on the list.

**Comment by treydock** [comment]
@ghoneycutt No explicit checkbox for README update.  Do we want to move examples and other documentation to puppet-strings where possible or also put examples in README?

**Comment by ghoneycutt** [comment]
Added a README button. It should conform to their template.

https://puppet.com/docs/puppet/5.5/modules_documentation.html

The first example should be the minimal installation and a single check.

**Comment by ghoneycutt** [comment]
@treydock could you double check the buttons above. Are we missing anything that needs to be done? Things that are done that can be checked off?

**Comment by treydock** [comment]
Items that can be checked off:

* EL6
* Ubuntu 18.04 - only issue thus far has been Vagrant which seems to now work with latest vagrant and latest box.
* document config approach - this is mentioned under Limitations of README merged in #933 

Items with open PRs:

* event - #920 
* extension - #931 

While debugging ubuntu-18.04 in Vagrant I noticed still some code in tests directory from sensu1 that needs to be cleaned up.

**Comment by ghoneycutt** [comment]
I can't get EL6 going.

```
Installing Virtualbox Guest Additions 5.2.12 - guest version is unknown
Verifying archive integrity... All good.
Uncompressing VirtualBox 5.2.12 Guest Additions for Linux........
VirtualBox Guest Additions installer
Copying additional installer modules ...
Installing additional modules ...
VirtualBox Guest Additions: Building the VirtualBox Guest Additions kernel modules.
This system is currently not set up to build kernel modules.
Please install the Linux kernel "header" files matching the current kernel
for adding new hardware support to the system.
The distribution packages containing the headers are probably:
    kernel-devel kernel-devel-2.6.32-696.28.1.el6.x86_64
VirtualBox Guest Additions: Starting.
VirtualBox Guest Additions: Building the VirtualBox Guest Additions kernel modules.
This system is currently not set up to build kernel modules.
Please install the Linux kernel "header" files matching the current kernel
for adding new hardware support to the system.
The distribution packages containing the headers are probably:
    kernel-devel kernel-devel-2.6.32-696.28.1.el6.x86_64
An error occurred during installation of VirtualBox Guest Additions 5.2.12. Some functionality may not work as intended.
In most cases it is OK that the "Window System drivers" installation failed.
VirtualBox Guest Additions: Starting.
VirtualBox Guest Additions: Building the VirtualBox Guest Additions kernel modules.
This system is currently not set up to build kernel modules.
Please install the Linux kernel "header" files matching the current kernel
for adding new hardware support to the system.
The distribution packages containing the headers are probably:
    kernel-devel kernel-devel-2.6.32-696.28.1.el6.x86_64
modprobe vboxguest failed
The log file /var/log/vboxadd-setup.log may contain further information.
Unmounting Virtualbox Guest Additions ISO from: /mnt
==> el6-agent: Checking for guest additions in VM...
    el6-agent: No guest additions were detected on the base box for this VM! Guest
    el6-agent: additions are required for forwarded ports, shared folders, host only
    el6-agent: networking, and more. If SSH fails on this machine, please install
    el6-agent: the guest additions and repackage the box to continue.
    el6-agent:
    el6-agent: This is not an error message; everything may continue to work properly,
    el6-agent: in which case you may ignore this message.
==> el6-agent: Setting hostname...
==> el6-agent: Configuring and enabling network interfaces...
    el6-agent: SSH address: 127.0.0.1:2200
    el6-agent: SSH username: vagrant
    el6-agent: SSH auth method: private key
==> el6-agent: Mounting shared folders...
    el6-agent: /vagrant => /Users/gh/git/sensu-puppet
Vagrant was unable to mount VirtualBox shared folders. This is usually
because the filesystem "vboxsf" is not available. This filesystem is
made available via the VirtualBox Guest Additions and kernel module.
Please verify that these guest additions are properly installed in the
guest. This is not a bug in Vagrant and is usually caused by a faulty
Vagrant box. For context, the command attempted was:

mount -t vboxsf -o uid=500,gid=500 vagrant /vagrant

The error output from the command was:

/sbin/mount.vboxsf: mounting failed with the error: No such device
```

**Comment by ghoneycutt** [comment]
ubuntu 14 gives

```
==> ubuntu1404-agent: Running provisioner: shell...
    ubuntu1404-agent: Running: inline script
    ubuntu1404-agent: Error: Could not run: Could not find file /vagrant/tests/sensu-agent-sensu_gem.pp
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
```

**Comment by treydock** [comment]
@ghoneycutt Issue with el6 in Vagrant appears to be fact box doesn't ship with latest kernel and when the guest addition logic adds `kernel-headers` it adds the latest available kernel headers and not the ones for kernel running on the box.  Logging into the box, updating kernel, and reloading fixes the box.

The issue with Ubuntu 14.04 box is issue with Vagrantfile I've opened PR #934

**Comment by treydock** [comment]
@ghoneycutt Need a checkbox to add `ensure => absent` support to `sensu_asset`.  This is opened here: https://github.com/sensu/sensu-go/issues/988

**Comment by treydock** [comment]
sensu-go appears to be adding cli support to manage backend cluster members.  Should probably add checkbox for cluster management.

**Comment by treydock** [comment]
@ghoneycutt config can be checked off via #938.  Need a checkbox to add `ensure => absent` support to sensu_asset. This is opened here: sensu/sensu-go#988.  The provider for sensu_asset supports delete but it causes errors when invoked, the acceptance tests explicitly skip testing the deletion of assets.  Only change necessary for sensu_asset is removing the skip here: https://github.com/sensu/sensu-puppet/blob/sensu2/spec/acceptance/sensu_asset_spec.rb#L54

**Comment by treydock** [comment]
@ghoneycutt Can check off `extension provider code is cleaned up` via #1013 .

**Comment by treydock** [comment]
@ghoneycutt User type is done but lacks `ensure => absent` similar to assets: https://github.com/sensu/sensu-go/issues/2540
